### ISSUE TITLE
universe inconsistency

### ISSUE THREAD

**Issue by aa755** [c-corn/corn#16]
I don't know if this is a bug in Coq or CoRN, but I get a universe inconsistency at the 2nd line (Using Coq 8.4pl3):

Require Import MathClasses.theory.finite_sets.
Require Import CoRN.algebra.CSetoidInc.

I encountered this problem when I was trying to import all CoRN files, that I can search for lemmas I need using SearchAbout/SearchPattern. Is there a workaround to search entire CoRN for lemmas? Are there some files which I can import to search a large part of CoRN/MathClasses?

**Comment by spitters** [comment]
Closing this, as we are now following master.
