### ISSUE TITLE
typeclass resolution confusing addition and multiplication

### ISSUE THREAD

**Issue by aa755** [c-corn/corn#23]
This issue is about MathClasses. But the MathClasses repo does not seem to have issues enabled.

(* This is how the Plus and Mult classes are currently defined in interfaces.canonical_names*)
Class Plus A := plus: A -> A -> A.
Class Mult A := mult: A -> A -> A.

(* The definition below typechecks. This often causes typeclass resolution
to pick a Plus instance for Mult, or vice versa, and then get all confused. *)
Definition plusAsMult (A:Type) (p:Plus A) : Mult A := p.

(* _Perhaps Plus and Mult should be defined as below?_  *)

Class PPlus A := {pplus: A -> A -> A}.
Class MMult A := {mmult: A -> A -> A}.

(* This does not typecheck, which is good! *)
Definition pplusAsMult (A:Type) (p:PPlus A) : MMult A := p.

**Comment by spitters** [comment]
This is intended, an abelian monoid (where we use +) is also an instance of a monoid (where we use *).
Do you see a solution without breaking that?

**Comment by aa755** [comment]
I tried a solution in the following commit:
https://github.com/aa755/math-classes/commit/6895588122eaeb4e2c65633248780a94d21b460c

By appropriately redefining  plus_is_sg_op and mult_is_sg_op, the existing definitions of abelian monoid and monoid can be reused without any change:

https://github.com/aa755/math-classes/commit/6895588122eaeb4e2c65633248780a94d21b460c#diff-f1d3393d9d116e2ee8a37ff8aa29ec82R161

I revived a large part of MathClasses to cope with this change in the definition of Plus and Mult.
If there are no concerns about the change, I can try to finish reviving all of MathClasses, and submit a pull request.

**Comment by spitters** [comment]
Your commit does seem to be quite a bit more verbose.
Don't you think that's a reason for not changing it?

**Comment by aa755** [comment]
For me, the cost of that verbosity is negligible compared to the hours I have wasted trying to debug typeclass resolution issues. In many cases, I found that the root cause was a confusion between `Plus` and `Mult` instances. To avoid such confusion, I had to manually provide many implicit arguments (at least the instances of Plus and Mult that were being confused). Hence, this change may actually reduce verbosity in applications of MathClasses.

I will probably adopt this change in my fork, and report back on the experience, especially if there is a significant impact on typeclass resolution. There are still many potential causes of confusion, e.g. the types of classes `One` and `Zero` are definitionally equal.

**Comment by spitters** [comment]
Fair enough. We've traded a bit of (initial?) verbosity for predictability,
so we could do it again.
This seems like a reasonable change.

I like forward to the pull request.

**Comment by spitters** [comment]
@aa755 Did you ever send a PR to math-classes? I'd be happy to pull that one. With the help of the coqdevs, we now have travis etc set up for math-classes too.

**Comment by aa755** [comment]
Sorry for the late response. IIRC, even after spending several hours, I didn't manage to completely port CoRN to the changes proposed in this PR. I am closing the PR for now.
