### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by siddharthist** [c-corn/corn#31]
Would you all be interested in a pull request providing a `.travis.yml` similar to (probably the same as) [my PR at math-classes](https://github.com/math-classes/math-classes/pull/13)?

**Comment by spitters** [comment]
Yes, that would be great.

**Comment by siddharthist** [comment]
@spitters I'm having [some trouble building in Travis](https://travis-ci.org/siddharthist/corn/builds/176199472). Is there some step I should take to download math-classes before building corn? Should I `opam install` it?

Might be good for the README as well :)

**Comment by spitters** [comment]
Yes, opam is probably the way to go. We went back and forth a bit. We used to use git submodules, but they don't interact very well with opam, which is what the coq-devs want. So, the last changes I made where to use opam.
