### ISSUE TITLE
[math-classes] Should the inner product be proper with respect to equivalence?

### ISSUE THREAD

**Issue by siddharthist** [c-corn/corn#36]
In our discussion on #30, we decided that `sm` should be proper with respect to `equiv`. Does that same reasoning hold for `inprod`? My intuition tells me it should, as I need that property to prove the following lemma about orthogonal projections:
```coq
Section orthogonal_projection.
  Context `{InnerProductSpace K V}.

  Definition proj (u v : V) : V := (⟨ u , v ⟩ / (⟨ u , u ⟩)) · u.

  Lemma lemma1 : forall (c : K) (u1 u2 v : V), u1 = c · u2 -> proj u1 v = proj u2 v.
``` 
Adding the following lines to `vectorspace.v` allows me to rewrite using the equality hypothesis:
```
Notation "(⟨⟩)" := (inprod) (only parsing) : mc_scope.
[...]
Class InnerProductSpace (K V : Type)
[...]
   ; inprod_proper  :> Proper ((=) ==> (=) ==> (=)) (⟨⟩)
```
I'm happy to make a pull request if this seems appropriate!

**Comment by spitters** [comment]
Yes! Thanks for spotting that. Please send a PR.

**Comment by siddharthist** [comment]
Fixed in https://github.com/math-classes/math-classes/pull/17
