### ISSUE TITLE
[math-classes] Additional axiom on inner product spaces: 0 = ⟨v,v⟩ iff v = mon_unit 

### ISSUE THREAD

**Issue by siddharthist** [c-corn/corn#37]
The [Wikipedia definition of an inner product space](https://en.wikipedia.org/wiki/Inner_product_space#Definition) has the following extra axiom: 
```coq
0 = ⟨v,v⟩ <-> v = mon_unit 
```
which isn't present in the current formalism. Should we rewrite the positivity rules as follows?
```coq
   ; in_pos_def1    :> ∀ v, PropHolds (0 ≤ ⟨v,v⟩)
   ; in_pos_def2    :> ∀ v, 0 = ⟨v,v⟩ <-> v = mon_unit
   }.
```

**Comment by spitters** [comment]
Yes, well spotted. Also, it would be natural to make a normed space out of an inner product space.

**Comment by siddharthist** [comment]
Fixed in https://github.com/math-classes/math-classes/pull/17
