### ISSUE TITLE
Building on OS X

### ISSUE THREAD

**Issue by jwiegley** [c-corn/corn#9]
Because OS X uses a case-insensitive filesystem, I'm unable to build corn due to errors such as:

```
Error: The file /private/var/folders/4j/br7bdhjx4b384_snb2087gt00000gn/T/nix-build-coq-corn-8.4-318d7dd8.drv-2/git-export/math-classes/src/implementations/Bool.vo contains library
MathClasses.implementations.bool and not library
MathClasses.implementations.Bool
```

**Comment by bmsherman** [comment]
This issue is resolved by the currently open pull request https://github.com/c-corn/corn/pull/21 (at least on my Mac).

**Comment by bmsherman** [comment]
Likely this issue is now resolved since pull request https://github.com/c-corn/corn/pull/24 was incorporated.
